"""initial: full schema with sprint 1-4 improvements

Revision ID: 5681eab83f3a
Revises: 
Create Date: 2026-07-07 01:08:20.187742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5681eab83f3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('error_type', sa.String(length=32), nullable=False),
    sa.Column('thinking_type', sa.String(length=32), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_patterns_user_id'), 'error_patterns', ['user_id'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('thinking_type', sa.String(length=32), nullable=False),
    sa.Column('concept_keywords', sa.Text(), nullable=True),
    sa.Column('task_summary', sa.Text(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetition_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_items_user_id'), 'review_items', ['user_id'], unique=False)
    op.add_column('exercise_sessions', sa.Column('prompt_version', sa.String(length=16), nullable=True))
    op.add_column('exercise_sessions', sa.Column('error_type', sa.String(length=32), nullable=True))
    op.add_column('thinking_profiles', sa.Column('score_history', sa.Text(), nullable=True))
    op.add_column('thinking_profiles', sa.Column('current_level', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('segment', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('segment_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('daily_streak', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_daily_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('total_sessions', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('badges', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'badges')
    op.drop_column('users', 'total_sessions')
    op.drop_column('users', 'last_daily_at')
    op.drop_column('users', 'daily_streak')
    op.drop_column('users', 'segment_updated_at')
    op.drop_column('users', 'segment')
    op.drop_column('thinking_profiles', 'current_level')
    op.drop_column('thinking_profiles', 'score_history')
    op.drop_column('exercise_sessions', 'error_type')
    op.drop_column('exercise_sessions', 'prompt_version')
    op.drop_index(op.f('ix_review_items_user_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_error_patterns_user_id'), table_name='error_patterns')
    op.drop_table('error_patterns')
    # ### end Alembic commands ###
